server.port=8080

spring.application.name=crm-backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SUPABASE_DB_URL:jdbc:h2:mem:crmdb}
spring.datasource.username=${SUPABASE_DB_USERNAME:sa}
spring.datasource.password=${SUPABASE_DB_PASSWORD:}

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
